# PyTorch Tensors

## What is a Tensor in PyTorch

In PyTorch, a Tensor is the fundamental data structure — basically a multi-dimensional array that can run on both CPU and GPU, similar to NumPy’s `ndarray` but with extra powers:

- **Stores numerical data**
  - Scalars: `tensor(3.14)` → 0D
  - Vectors: `tensor([1, 2, 3])` → 1D
  - Matrices: `tensor([[1, 2], [3, 4]])` → 2D
  - Higher-dimensional arrays for images, videos, batches, etc.
- **Supports automatic differentiation**
  - If `requires_grad=True`, PyTorch tracks operations on the tensor so it can compute gradients automatically (used for training neural networks).
- **Optimized for hardware acceleration**
  - Can live in CPU or GPU memory
  - Operations can be vectorized and parallelized for speed
- **Interoperable with NumPy**
  - You can easily convert between `numpy.ndarray` and `torch.Tensor` without copying data (when on CPU)

If you think in math terms:

> **Tensor** — generalization of scalars (0D), vectors (1D), and matrices (2D) to n-dimensions.

In machine learning, tensors represent data (features, images, audio) and model parameters.

| Concept in Math         | In Linear Algebra                    | In PyTorch (or NumPy) |
| ----------------------- | ------------------------------------ | --------------------- |
| **Scalar**              | Single number                        | 0-D tensor            |
| **Vector**              | Ordered list of numbers (1D array)   | 1-D tensor            |
| **Matrix**              | Table of numbers with rows & columns | 2-D tensor            |
| **Higher-order tensor** | Multi-indexed array (e.g., 3D cube)  | 3-D+ tensor           |
Higher-rank tensors have 3+ axes, which don’t have a special name in classical linear algebra but appear naturally in physics, graphics, and ML (e.g., RGB image batches).

Operations you know for vectors (addition, scalar multiplication, dot product) are _special cases_ of tensor operations. They work on any dimension, often in a _vectorized_ way.

### Real-world Examples

| Name               | Rank | PyTorch example                                  | Shape          | Real‑world example                                  |
|--------------------|------|---------------------------------------------------|----------------|-----------------------------------------------------|
| Scalar             | 0    | `torch.tensor(21.5)`                              | `()`           | Temperature value (e.g., 21.5 °C)                   |
| Vector             | 1    | `torch.randn(300)`                                | `(300,)`       | Word embedding (300‑D)                              |
| Matrix             | 2    | `torch.randn(480, 640)`                           | `(480, 640)`   | Grayscale image (height × width)                    |
| Rank‑3 tensor      | 3    | `torch.randn(480, 640, 3)`                        | `(480, 640, 3)`| RGB image (height × width × channels)               |

## Creating 1D Tensors

In [2]:
import torch

### From a Python list

In [3]:
t = torch.tensor([1, 2, 3])

In [4]:
t

tensor([1, 2, 3])

In [5]:
t.shape

torch.Size([3])

> 💡 Best for small, fixed data.

Data type (`dtype`) is inferred but can be set explicitly:

In [7]:
t = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

### Using `torch.arange`

In [8]:
t = torch.arange(0, 5)

In [9]:
t

tensor([0, 1, 2, 3, 4])

In [10]:
t = torch.arange(0, 10, 2)

In [11]:
t

tensor([0, 2, 4, 6, 8])

Works like Python’s range, but returns a tensor.

### Using `torch.linspace`

In [12]:
t = torch.linspace(0, 1, steps=5)

In [13]:
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Creates evenly spaced numbers between start and end.

### Random initialization

In [18]:
t = torch.rand(5) # uniform

In [15]:
t

tensor([0.2289, 0.2132, 0.2098, 0.1100, 0.2262])

In [16]:
t = torch.randn(5) # normal distribution (mean=0, std=1)

In [17]:
t

tensor([-2.9893,  1.4838,  0.9708, -0.6635,  1.1160])

### From NumPy arrays

In [19]:
import numpy as np

In [20]:
arr = np.array([1, 2, 3])
t = torch.from_numpy(arr)

In [21]:
t

tensor([1, 2, 3])

⚠️ Shares memory with the NumPy array (changes in one affect the other if on CPU).

---

> A 1D tensor’s shape will be something like (n,) — one axis, length n.

---

## Addition & scalar multiplication

How it works in practice:

In [29]:
import torch

# Create two 1D tensors (vectors)
a = torch.tensor([2.0, -1.0, 3.0])
b = torch.tensor([1.0, 4.0, -2.0])

# Vector addition
sum_ab = a + b # tensor([3., 3., 1.])

# Scalar multiplication
scalar_mult = 3 * a # tensor([ 6., -3.,  9.])

### Manual verification

In [28]:
manual_sum = torch.tensor([a[0]+b[0], a[1]+b[1], a[2]+b[2]]) # same as sum_ab

In [25]:
manual_sum

tensor([3., 3., 1.])

In [26]:
manual_scalar = torch.tensor([3*a[0], 3*a[1], 3*a[2]]) # same as scalar_mult

In [27]:
manual_scalar

tensor([ 6., -3.,  9.])

This is exactly how you’d do it in linear algebra — PyTorch just vectorizes it.

### Note about vectorization

When we say “PyTorch just vectorizes it”, we mean that PyTorch applies the operation to every element of the tensor at once, without you writing an explicit `for` loop.

Non-vectorized (manual loop):

In [30]:
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

In [31]:
result

[tensor(3.), tensor(3.), tensor(1.)]

Vectorized (PyTorch style):

In [32]:
result = a + b

In [33]:
result

tensor([3., 3., 1.])

PyTorch does the looping internally in optimized C/CUDA code, so:

- It’s much faster (can use CPU SIMD instructions or GPU parallelism)
- It’s cleaner to read and write
- The same syntax works for scalars, vectors, matrices, and higher-rank tensors

So when you write `a + b` in PyTorch, it’s doing element-wise addition across all elements at once — that’s vectorization.

<img src="img/01.png" width="350">